name: getAllRepliesToKnownPosts
concurrency: get_context

on:
  workflow_dispatch:
  schedule:
     - cron: '9,19,29,39,49,59 * * * *'
     
jobs:
  run:
    runs-on: ubuntu-latest
    environment: mastodon
    steps:
      - name: Checkout original repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
         python-version: '3.10'
         cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Download all workflow run artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          name: artifacts
          workflow: get_context.yml
          if_no_artifact_found: warn
          path: artifacts
      - run: python find_posts.py --lock-hours=0 --access-token=${{ secrets.ACCESS_TOKEN }} -c="./config.json"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            artifacts
      - name: Keep workflow alive
        uses: gautamkrishnar/keepalive-workflow@v1
        if: always()
